version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - create_backend
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file backend.yml \
              --stack-name udapeople-backend
workflows:
  my_workflow:
    jobs:
      - create_backend
